(function(){
'use strict';
const A=()=>DBApi,q=s=>document.querySelector(s),e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),m=n=>new Intl.NumberFormat('ar-EG',{style:'currency',currency:'EGP'}).format(+n||0);
const S=['pending','confirmed','preparing','out_for_delivery','delivered','cancelled'],L={pending:'جديد',confirmed:'مؤكد',preparing:'جاري التجهيز',out_for_delivery:'في الطريق',delivered:'تم التسليم',cancelled:'ملغي'};let O=[],P=[],C=[],Z=[];
function gate(){document.body.innerHTML='<div class="staff-gate"><div class="staff-card"><span class="eyebrow">DELIVER BOOKS</span><h1>لوحة الإدارة</h1><p>كود الإدارة</p><form id="g"><input id="code" type="password" required><button class="button button-dark">دخول</button><small id="err"></small></form></div></div>';q('#g').onsubmit=async x=>{x.preventDefault();try{await A().staffLogin(q('#code').value,'admin');boot()}catch(z){q('#err').textContent=z.message}}}
function shell(){document.body.innerHTML='<div class="admin-shell"><aside class="admin-side"><div class="admin-brand"><b>D</b><span>DELIVER BOOKS<small>ADMIN</small></span></div><nav><button data-tab="orders">الطلبات</button><button data-tab="products">الكتب</button><button data-tab="categories">الأقسام</button><button data-tab="zones">التوصيل</button></nav><button id="logout">خروج</button></aside><main class="admin-main"><header class="admin-top"><div><span class="eyebrow">OPERATIONS</span><h1 id="title">الطلبات</h1></div><button id="refresh" class="button button-outline">تحديث</button></header><section id="view"></section></main></div>'}
function orders(){q('#view').innerHTML='<div class="admin-stats"><div><b>'+O.length+'</b><span>إجمالي</span></div><div><b>'+O.filter(x=>!['delivered','cancelled'].includes(x.status)).length+'</b><span>نشطة</span></div><div><b>'+m(O.filter(x=>x.status==='delivered').reduce((a,x)=>a+(+x.total||0),0))+'</b><span>مُسلّمة</span></div></div><div class="admin-toolbar"><input id="search" placeholder="بحث بالاسم أو رقم الطلب"><select id="filter"><option value="">كل الحالات</option>'+S.map(x=>'<option value="'+x+'">'+L[x]+'</option>').join('')+'</select></div><div class="orders-list" id="list">'+O.map(row).join('')+'</div>';q('#search').oninput=paint;q('#filter').onchange=paint}
function row(o){return'<article class="admin-order" data-id="'+o.id+'"><div class="order-top"><div><b>'+e(o.orderNumber)+'</b><small>'+new Date(o.createdAt).toLocaleString('ar-EG')+'</small></div><select data-status>'+S.map(s=>'<option '+(s===o.status?'selected':'')+' value="'+s+'">'+L[s]+'</option>').join('')+'</select></div><div class="order-customer"><strong>'+e(o.customerName)+'</strong><span>'+e(o.customerPhone)+'</span><span>'+e(o.address)+'</span></div><div class="order-items">'+(o.items||[]).map(i=>'<div><span>'+e(i.nameAr||i.nameEn)+' × '+i.quantity+'</span><b>'+m(i.lineTotal)+'</b></div>').join('')+'</div><div class="order-total"><span>الإجمالي</span><b>'+m(o.total)+'</b></div><div class="order-actions"><button data-print class="button button-outline">طباعة ورقة الطلب</button></div></article>'}
function paint(){let t=(q('#search').value||'').toLowerCase(),f=q('#filter').value;q('#list').innerHTML=O.filter(o=>(!f||o.status===f)&&[o.orderNumber,o.customerName,o.customerPhone,o.address].join(' ').toLowerCase().includes(t)).map(row).join('')}
async function loadOrders(){O=await A().adminOrders();orders()}
function products(){q('#view').innerHTML='<div class="admin-section-head"><h2>الكتب</h2><button id="newp" class="button button-dark">+ كتاب</button></div><div class="admin-list">'+P.map(p=>'<div><b>'+e(p.nameAr)+'</b><span>'+m(p.price)+'</span><span>مخزون '+p.stock+'</span><button data-editp="'+p.id+'">تعديل</button></div>').join('')+'</div>'}
function productForm(p={}){q('#view').innerHTML='<div class="admin-form-card"><h2>'+(p.id?'تعديل':'إضافة')+' كتاب</h2><form id="pf" class="form-grid"><input type="hidden" name="id" value="'+(p.id||'')+'"><label class="field"><span>الاسم العربي</span><input name="nameAr" required value="'+e(p.nameAr||'')+'"></label><label class="field"><span>English</span><input name="nameEn" value="'+e(p.nameEn||'')+'"></label><label class="field"><span>Slug</span><input name="slug" required value="'+e(p.slug||'')+'"></label><label class="field"><span>القسم</span><select name="categoryId"><option value="">بدون</option>'+C.map(c=>'<option value="'+c.id+'" '+(String(c.id)===String(p.categoryId)?'selected':'')+'>'+e(c.nameAr)+'</option>').join('')+'</select></label><label class="field"><span>السعر</span><input name="price" type="number" min="0" step=".01" value="'+(p.price||0)+'"></label><label class="field"><span>المخزون</span><input name="stock" type="number" min="0" value="'+(p.stock||0)+'"></label><label class="field"><span>المؤلف</span><input name="author" value="'+e(p.author||'')+'"></label><label class="field"><span>الناشر</span><input name="publisher" value="'+e(p.publisher||'')+'"></label><label class="field field-wide"><span>الوصف</span><textarea name="descriptionAr">'+e(p.descriptionAr||'')+'</textarea></label><label><input type="checkbox" name="featured" '+(p.featured?'checked':'')+'> مميز</label><button class="button button-dark field-wide">حفظ</button></form></div>';q('#pf').onsubmit=async x=>{x.preventDefault();let p=Object.fromEntries(new FormData(x));p.featured=x.target.featured.checked;await A().saveProduct(p);await loadProducts();products()}}
async function loadProducts(){P=await A().adminProducts()}
function categories(){q('#view').innerHTML='<div class="admin-section-head"><h2>الأقسام</h2><button id="newc" class="button button-dark">+ قسم</button></div><div class="admin-list">'+C.map(c=>'<div><b>'+e(c.nameAr)+'</b><span>'+e(c.slug)+'</span><button data-editc="'+c.id+'">تعديل</button></div>').join('')+'</div>'}
function catForm(c={}){q('#view').innerHTML='<div class="admin-form-card"><h2>القسم</h2><form id="cf" class="form-grid"><input type="hidden" name="id" value="'+(c.id||'')+'"><label class="field"><span>العربي</span><input name="nameAr" required value="'+e(c.nameAr||'')+'"></label><label class="field"><span>English</span><input name="nameEn" value="'+e(c.nameEn||'')+'"></label><label class="field"><span>Slug</span><input name="slug" required value="'+e(c.slug||'')+'"></label><label class="field"><span>الترتيب</span><input name="sortOrder" type="number" value="'+(c.sortOrder||0)+'"></label><button class="button button-dark field-wide">حفظ</button></form></div>';q('#cf').onsubmit=async x=>{x.preventDefault();await A().saveCategory(Object.fromEntries(new FormData(x)));C=await A().adminCategories();categories()}}
function zones(){q('#view').innerHTML='<div class="admin-section-head"><h2>مناطق التوصيل</h2><button id="newz" class="button button-dark">+ منطقة</button></div><div class="admin-list">'+Z.map(z=>'<div><b>'+e(z.nameAr)+'</b><span>'+m(z.fee)+'</span><span>'+(z.freeAbove?('مجاني فوق '+m(z.freeAbove)):'')+'</span><button data-editz="'+z.id+'">تعديل</button></div>').join('')+'</div><p class="admin-note">لا توجد رسوم افتراضية؛ هذه القيم هي التي يستخدمها الطلب.</p>'}
function zoneForm(z={}){q('#view').innerHTML='<div class="admin-form-card"><h2>منطقة التوصيل</h2><form id="zf" class="form-grid"><input type="hidden" name="id" value="'+(z.id||'')+'"><label class="field"><span>العربي</span><input name="nameAr" required value="'+e(z.nameAr||'')+'"></label><label class="field"><span>English</span><input name="nameEn" value="'+e(z.nameEn||'')+'"></label><label class="field"><span>الرسوم</span><input name="fee" type="number" min="0" step=".01" required value="'+(z.fee??'')+'"></label><label class="field"><span>مجاني فوق</span><input name="freeAbove" type="number" min="0" step=".01" value="'+(z.freeAbove??'')+'"></label><button class="button button-dark field-wide">حفظ</button></form></div>';q('#zf').onsubmit=async x=>{x.preventDefault();await A().saveZone(Object.fromEntries(new FormData(x)));Z=await A().adminZones();zones()}}
async function route(t){q('#title').textContent={orders:'الطلبات',products:'الكتب',categories:'الأقسام',zones:'التوصيل'}[t];document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('is-active',x.dataset.tab===t));if(t==='orders')await loadOrders();if(t==='products'){await loadProducts();products()}if(t==='categories'){C=await A().adminCategories();categories()}if(t==='zones'){Z=await A().adminZones();zones()}}
function bind(){document.addEventListener('click',async x=>{let t=x.target.closest('[data-tab]');if(t)route(t.dataset.tab);if(x.target.closest('#refresh'))route(document.querySelector('[data-tab].is-active').dataset.tab);if(x.target.closest('#logout')){await A().staffLogout();location.reload()}if(x.target.closest('#newp'))productForm();if(x.target.closest('#newc'))catForm();if(x.target.closest('#newz'))zoneForm();let p=x.target.closest('[data-editp]');if(p){await loadProducts();productForm(P.find(v=>String(v.id)===p.dataset.editp))}let c=x.target.closest('[data-editc]');if(c){C=await A().adminCategories();catForm(C.find(v=>String(v.id)===c.dataset.editc))}let z=x.target.closest('[data-editz]');if(z){Z=await A().adminZones();zoneForm(Z.find(v=>String(v.id)===z.dataset.editz))}let pr=x.target.closest('[data-print]');if(pr){let o=O.find(v=>v.id===pr.closest('.admin-order').dataset.id);sessionStorage.setItem('db_print_order',JSON.stringify(o));window.open('print.html','_blank')}let s=x.target.closest('[data-status]');if(s){let o=O.find(v=>v.id===s.closest('.admin-order').dataset.id);if(o&&s.value!==o.status){await A().updateOrderStatus(o.id,s.value,'تم التحديث من الإدارة');loadOrders()}}})}
async function boot(){shell();bind();await route('orders');setInterval(()=>loadOrders().catch(()=>{}),15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>DBApi.staffToken()?boot():gate());else DBApi.staffToken()?boot():gate()
})();